services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: MAILJET_API_KEY
        value: your_mailjet_api_key
      - key: MAILJET_API_SECRET
        value: your_mailjet_api_secret
    # Optional: You can specify the port here, although Render typically auto-detects
    port: 5000
